### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by abbabaa** [techguy940/DiscordReactionVerifier#1]
it workes

**Comment by poojan2312** [comment]
it works? can i close this issue now?

**Comment by nompelis** [comment]
Does not work for me. Python3, Discord.py discord.py-2.0.1.tar.gz.

When I type ".setup" it does not actually perform the setup. I added a command to display messages using the "on_message()" hook, like this:

**@bot.event
async def on_message(message):
   #... stuff here**

And I see the ".setup" coming as a message. It is not received as a "command". Ideas?

**Comment by nompelis** [comment]
I have figured out how to fix this. A method to handle "onmessage()" takes all posted messages, and it sends them to the "process_command()" method. Then the message cascades to the command type methods.
